name: forpawssake
favicon: null
layout_spectrum: 0.5840003117918968
typography_spectrum: 0.5206298299599439
title: 'For Paws Sake! Pet Care'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3538661783095449
  lightness: 0.07030113390646875
  saturation: 0.6401637815870345
  rhythmicContrast: 0.5166930521372706
purpose: []
