name: forpawssake
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60324
title: 'For Paws Sake! Pet Care'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8fff39'
    - '#5b6d74'
    - '#d2d2d2'
    - '#a2acb0'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
